### ISSUE TITLE
Find out how IdentityServer3 auto-logs to NLog

### ISSUE THREAD

**Issue by NetChris** [NetChris/NetChris.NLog.Extensions#4]
It is able to log to NLog when the reference is available, but is OK with no reference available.

When analysis complete, put together a sample.

**Comment by shoff** [comment]
Curious if you figured this out? I too am trying to figure out how it "auto" works as it doesn't seem to autowork for me and the snarky replies by the IdentityServer devs are off-putting.

**Comment by NetChris** [comment]
Not yet.  But now looking at [Dominick's comment on this issue](https://github.com/IdentityServer/IdentityServer3/issues/1982#issuecomment-145349121), I'm guessing it's something in [LibLog](https://github.com/damianh/LibLog).  And since the LibLog NuGet package doesn't actually bring in references, but rather imports and transforms the single LibLog.cs file directly, this "no NLog reference" thing makes more sense.

I'll dig into how this works when I have time to focus, but I'll wager that's how it's done.

**Comment by okutlubay** [comment]
were you able to figure this out?

**Comment by NetChris** [comment]
No.  Right now, I'm just trusting it has to do with LibLog.  I haven't been able to really dig into this (especially since there's nothing broken).

**Comment by okutlubay** [comment]
It just doesn't hook up to NLog automatically as stated (I couldn't do it with Serilog.Sinks.NLog either, anyway...); but it does so to Serilog. And without Serilog, LibLog does not dump service level logs at all. Am I missing something?

**Comment by NetChris** [comment]
It's definitely just LibLog magic.  See [this](https://github.com/damianh/LibLog/wiki#transparent-logging-support).

**Comment by JosephDevlin** [comment]
Im stuck in this exact position. I cannot get IdentityServer to log to NLog and can find nothing online bar links to the docs which tell me nothing other than that it "just works". Their github samples pages has no link in the logging section https://github.com/identityserver/IdentityServer3.Samples

How are people managing to get Nlog wired up? Are you really just referencing the NLog package and having it work with no extra effort?
